// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYx8PTNNe7VdmHiDzy9kzcAdJyrix0xsU',
    appId: '1:217973990694:web:3682177404c8bdfc9c0de7',
    messagingSenderId: '217973990694',
    projectId: 'cruise-app-72ea2',
    authDomain: 'cruise-app-72ea2.firebaseapp.com',
    storageBucket: 'cruise-app-72ea2.appspot.com',
    measurementId: 'G-SYLQD8254W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-oOLf557ThTJuGRhmQIN-eJJNkxXxYsY',
    appId: '1:217973990694:android:ed4f9276c1e263ab9c0de7',
    messagingSenderId: '217973990694',
    projectId: 'cruise-app-72ea2',
    storageBucket: 'cruise-app-72ea2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaVzRtdHbSt0RcwndV-Gk2kDhDkt0_ym0',
    appId: '1:217973990694:ios:6b3ce16d6ed7a4c09c0de7',
    messagingSenderId: '217973990694',
    projectId: 'cruise-app-72ea2',
    storageBucket: 'cruise-app-72ea2.appspot.com',
    iosBundleId: 'com.example.cruiseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaVzRtdHbSt0RcwndV-Gk2kDhDkt0_ym0',
    appId: '1:217973990694:ios:6b3ce16d6ed7a4c09c0de7',
    messagingSenderId: '217973990694',
    projectId: 'cruise-app-72ea2',
    storageBucket: 'cruise-app-72ea2.appspot.com',
    iosBundleId: 'com.example.cruiseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYx8PTNNe7VdmHiDzy9kzcAdJyrix0xsU',
    appId: '1:217973990694:web:50414d796377f4cf9c0de7',
    messagingSenderId: '217973990694',
    projectId: 'cruise-app-72ea2',
    authDomain: 'cruise-app-72ea2.firebaseapp.com',
    storageBucket: 'cruise-app-72ea2.appspot.com',
    measurementId: 'G-GQJ7Q3NMQG',
  );
}
